sudo: required
language: ruby
notifications:
  email:
    recipients:
      - regis.aubarede@gmail.com
dist: trusty
sudo: required
rvm:
  - 2.2.0
before_install:
  - gem install bundler
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb  start"
  - sleep 3
script: "rake travis"
after_script:
  - sh -e /ext/init.d/xvfb stop