language: ruby
rvm:
  - 2.0.0
before_script:
  - sudo apt-get install libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb  start"
  - sleep 3
script: "rake travis"